development:
  stripe_key: ***REMOVED***
  shipwire_login: rromanchuk@gmail.com
  shipwire_password: ***REMOVED***

test:
  stripe_key: ***REMOVED***
  shipwire_login: rromanchuk@gmail.com
  shipwire_password: ***REMOVED***

production:
  stripe_key: pk_QheikYVHpeR004nuGdD2QN5QOf8q0
  shipwire_login: rromanchuk@gmail.com
  shipwire_password: ***REMOVED***